 
services: 
    server:
        image: ij42/jre-s6
        tty: true
        stdin_open: true
        mem_limit: 2048mb
        container_name: server
        ports:
            - 25565:25565
        volumes:
            - /home/server:/app/server
        restart: always
        environment:
            - TZ=Europe/Moscow # Timezone
            - PUID=1000  # User  ID `id $(whoami) -u`
            - PGID=985   # Group ID `id $(whoami) -g`
