name: Build Workflow

on:
  schedule:
    - cron:  '0 0 * * SUN'
  push:

jobs:
  build:
    continue-on-error: true
    strategy:
        fail-fast: false
        matrix:
            image: [ bytecode-viewer, discord, forkwork, keepassxc, spotify ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DOCKER
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./${{ matrix.image }}/Dockerfile
          tags: "${{ github.repository_owner }}/${{ matrix.image }}"
          push: true
